#include "nsISupports.idl"

[scriptable, uuid(0897d710-65ca-43fd-adfa-cb0b66555d2e)]
interface nsIKeepassCredentials : nsISupports {
    attribute AString username;
    attribute AString password;
};
